### PR TITLE
[LOOP-3323] Allow pause onboarding

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-3323

### CODE REVIEW

**Review by nhamming — APPROVED** [review]
I assume this isn't needed here. LGTM

**Comment by darinkrauss** [comment]
@nhamming I'm not sure I understand your comment. This is needed for DIY so that `LoopOnboarding` conforms to the updated `LoopKit` `OnboardingUI` protocol. What am I missing?

**Review by rickpasetto — APPROVED** [review]
LGTM

**Comment by nhamming** [comment]
> @nhamming I'm not sure I understand your comment. This is needed for DIY so that `LoopOnboarding` conforms to the updated `LoopKit` `OnboardingUI` protocol. What am I missing?

@darinkrauss I mean that I'm making the assumption that DIY onboarding doesn't need a suspend feature.

**Review by ps2 — APPROVED** [review]
LGTM. This goes away if tracking isSuspended is Loop's responsibility.

**Comment by darinkrauss** [comment]
No longer necessary with latest LoopKit changes.

**Pull request closed without merging**
